version: '3.7'
services:
        postgres:
                restart: always
                container_name: postgres
                build:
                        context: ./database
                ports:
                        - 5432:5432
        server:
                restart: always
                build:
                        context: ./backend
                command: python /app/manage.py runserver 0.0.0.0:8000
                ports:
                        - 8000:8000
                env_file: .env
                depends_on:
                        - postgres