version: '3.7'
services:
        postgres:
                container_name: postgres
                build:
                        context: ./database
                ports:
                        - 5432:5432
