# Generated by Django 3.0.8 on 2020-07-19 21:46

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONSTRUCTION', 'Construction'), ('SPECIAL_EVENT', 'Special Event'), ('INCIDENT', 'Incident'), ('WEATHER_CONDITION', 'Weather Condition'), ('ROAD_CONDITION', 'Road Condition')], max_length=17)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('TO_BE_VALIDATED', 'To be validated'), ('VALIDATED', 'Validated'), ('RESOLVED', 'Resolved')], default='TO_BE_VALIDATED', max_length=15)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
